title: David Munechika
tagline: Stamps President's Scholar at Georgia Tch
url: http://davidmunechika.github.io
baseurl: ""
# gems: [jekyll-paginate]
# paginate: 5

# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink: "/:title"
# relative_permalinks: true

sass:
  sass_dir: _sass
  style: compressed

author:
  name: David Munechika
  url: http://davidmunechika.github.io
  email: david.munechika@gmail.com

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'syntax'

excerpt_separator: <!--more-->

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
